require("dotenv").config({ path: "./config.env" });
const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const connectDB = require("./config/DB");
const cors = require("cors");
const cookieParser = require("cookie-parser");
const authRoute = require("./routes/authRoute");
const postRoute = require("./routes/postRoute");
const path = require("path");
app.use(cors({ credentials: true, origin: "http://localhost:5173" }));
app.use(express.json());
app.use(bodyParser.json({ limit: "30mb", extended: true }));
app.use(bodyParser.urlencoded({ limit: "30mb", extended: true }));
app.use(cookieParser());
app.use("/uploads", express.static(path.join(__dirname + "/uploads")));
app.use("/", authRoute);
app.use("/", postRoute);
connectDB();
app.listen(4000);
